# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Install Jekyll dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          gem install bundler jekyll

      - name: Build Jekyll site
        run: |
          bundle install
          jekyll build --destination _site

      - name: Verify build output
        run: ls -l _site  # ✅ Verificar que se crearon archivos

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages  # ✅ Asegurar el nombre del artifact
          path: _site         # ✅ Ruta de salida de Jekyll

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
